@id= 48a5c259-431b-4baa-8d3d-01eb81ee777f

PUT http://localhost:5170/market/{{id}}
Content-Type: application/json

{
    "name": "Badtz-Maru 2",
    "description": "male penguin with spiky hair",
    "startDateTime": "2024-02-06T02:25:00",
    "endDateTime": "2024-02-06T03:00:00",
    "traits": [
        "American",
        "Penguin",
        "Male"
    ]
}